# Generated by Django 2.2.1 on 2019-05-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='something about this author', max_length=1000),
            preserve_default=False,
        ),
    ]
